server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    max-connections: 20000
    connection-timeout: 10000ms
    threads:
      min-spare: 100
      max: 1000
  servlet:
    context-path: /juc
logging:
  level:
    com.xpf.juc: debug